package Controller;

public class QueryMakeReservation implements Query {

    private int id; //selection from list of itineraries generated by last query
    private String name; //passenger name

    public void generateResponse(){}
}
